### ISSUE TITLE
heatting

### ISSUE THREAD

**Issue by RakNetEx** [PixelExperience-Exynos/OTA#4]
cpu settings.
![Screenshot_20220513-151229_CPU-Z](https://user-images.githubusercontent.com/94397225/168280901-06c4d2ed-afff-4453-ba84-09387f4c3c80.png)
![Screenshot_20220513-151225_CPU-Z](https://user-images.githubusercontent.com/94397225/168280915-b58c47dd-f9e7-4671-ba85-b74544b8985a.png)
![Screenshot_20220513-151222_CPU-Z](https://user-images.githubusercontent.com/94397225/168280919-d958a5cc-c4e7-4e62-b2d4-ec500a17e49f.png)
![Screenshot_20220513-151221_CPU-Z](https://user-images.githubusercontent.com/94397225/168280928-a39113a9-53d0-40fd-961a-0e5190519b2b.png)
![Screenshot_20220513-151217_CPU-Z](https://user-images.githubusercontent.com/94397225/168280939-11f25fc0-78c4-4023-9343-d90459245d42.png)

**Comment by ExpressLuke** [comment]
This isn't a bug reporting forum for issues with rom, only if you have issues with OTA.
